title: Saad Wagle
logo: /IMG_6895.jpg
description: Welcome to my website! I am Saad.
show_downloads: false
theme: jekyll-theme-minimal

author:
  phone_number: 9004664648
  email: saad.wagle987@gmail.com
  linkedin_username: Saad Wagle
