title: Saad Wagle
phone_number: 9004664648
email: saad.wagle987@gmail.com
linkedin_username: Saad Wagle
logo: /IMG_6895.jpg
description: Welcome to my website! I am Saad, I have strong problem solving skills and a drive to unravel patterns and trends contributing to strategic decision making. I am confident that my enthusiasm and dedication to learn from experienced professionals will allow me to quickly become an asset.
show_downloads: false
theme: jekyll-theme-hydeout
