title: Saad Wagle
logo: /IMG_6895.jpg
description: I have strong problem solving skills and a drive to unravel patterns and trends contributing to strategic decision making. I am confident that my enthusiasm and dedication to learn from experienced professionals will allow me to quickly become an asset.
show_downloads: false
theme: jekyll-theme-minimal
